### ISSUE TITLE
Unciphering issue

### ISSUE THREAD

**Issue by Greensky-gs** [RichardDorian/enigma-machine#2]
There is actually a true issue (not as #1 x) )

The Enigma machine is supposed to be able to uncipher ciphered messages. Your package doesn't. It is kinda annoying, because we can cipher anything we want, we wont be able to read it back. Once again, it is what I constated, I could be wrong, but I didn't see anything about unciphering, neither in the readme, nor the typing.

Here is the code I used :
```js
const Enigma = require('enigma-machine')

const config = Enigma.generateEnigmaConfiguration()
const machine = Enigma.Enigma.generateFromEnigmaConfig(config)

const ciphered = machine.calculateString('hello there')
console.log(ciphered)

const uncipher = Enigma.Enigma.generateFromEnigmaConfig(config)
const deciphered = uncipher.calculateString(ciphered)

console.log(deciphered)
```

And here is the output :
```
clumlundefinedhfgnd
kyazczjbdebpcxcojjb
```

@RichardDorian (I allow myself to mention you, because I saw that the lib is 2 years old and I don't think you're watching it everyday)

**Comment by RichardDorian** [comment]
Hi, the issue is that you are creating two instances using the same config object. When ciphering data the Enigma instance will update the config object. Since you're using the same object for the two instances it updates the other instance config (since it is the same). It is like having one machine rotating the rotors of the other machine at the same time it rotates its rotors.
To fix this issue you can deep copy the config object (using the spread operator or the new [Default Composer](https://github.com/aralroca/default-composer) lib) and use it to create the second enigma instance.

**Comment by Greensky-gs** [comment]
I may be stupid, there's probably something I did wrong, but it still doesn't work. I tried this 

```js
const Enigma = require('enigma-machine')

const config = Enigma.generateEnigmaConfiguration()
const uncipherConfig = {...config}

const machine = Enigma.Enigma.generateFromEnigmaConfig(config)
const ciphered = machine.calculateString('hello there')

console.log(ciphered)

const uncipher = Enigma.Enigma.generateFromEnigmaConfig(uncipherConfig)

const deciphered = uncipher.calculateString(ciphered)
console.log(deciphered)
```

And it still outputs something different.
Also, I noticed that the input string length is 11 and the ciphered length is 19

Edit: the length is different because we cannot input spaces, but when I input only "hello", it still doesn't decipher correctly

**Comment by RichardDorian** [comment]
The config object is multiple nested objects. Therefore, you need to use multiple time the spread operator to make a full copy of the config. I strongly recommend you use the [Default Composer](https://github.com/aralroca/default-composer) library. If you really don't want to use the Default Composer library, you can serialize the config and deserialize it using JSON like I did here:

```js
const { Enigma, generateEnigmaConfiguration } = require('.');

const config = generateEnigmaConfiguration();
const configCopy = JSON.parse(JSON.stringify(config));

const cipher = Enigma.generateFromEnigmaConfig(config);
const decipher = Enigma.generateFromEnigmaConfig(configCopy);

const encrypted = cipher.calculateString('helloworld');
const decrypted = decipher.calculateString(encrypted);

console.log(decrypted); // helloworld
```

**Comment by RichardDorian** [comment]
By the way, this is a very, very old project and the code quality is awful and the variable/function naming are everything but usable.
